import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import cx from "clsx";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-primary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          `${poppins.variable} font-sans`,
          "max-w-7xl mx-auto mt-8"
        )}
      >
        {children}
      </body>
    </html>
  );
}
