import { FilterObj } from "@/lib/types";

export const filterObj: FilterObj = {
  projectType: {
    label: "Project Type",
    options: [
      {
        label: "Landing page",
        value: "landing-page",
        price: 500,
      },
      {
        label: "CRM",
        value: "crm",
        price: 4000,
      },
      {
        label: "SaaS",
        value: "saas",
        price: 5000,
      },
      {
        label: "Ecommerce store",
        value: "e-commerce",
        price: 3000,
      },
      {
        label: "Classifieds",
        value: "classifieds",
        price: 2500,
      },
      {
        label: "Marketplace",
        value: "marketplace",
        price: 4000,
      },
      {
        label: "Mobile app",
        value: "mobile-app",
        price: 7000,
      },
    ],
  },
  design: {
    label: "Design",
    options: [
      {
        label: "Wireframes",
        value: "wireframes",
        price: 500,
      },
      {
        label: "Low-Fidelity (Lo-Fi) Design",
        value: "lofi",
        price: 1000,
      },
      {
        label: "High-Fidelity (Hi-Fi) Design",
        value: "hifi",
        price: 2000,
      },
      {
        label: "Minimal Viable Product (MVP) Design",
        value: "mvp",
        price: 1500,
      },
      {
        label: "Not Required",
        value: "not-required",
        price: 0,
      },
    ],
  },
  development: {
    label: "Development",
    options: [
      {
        label: "Basic Development",
        value: "basic-development",
        price: 2000,
      },
      {
        label: "Standard Development",
        value: "standard-development",
        price: 4000,
      },
      {
        label: "Custom Development",
        value: "custom-development",
        price: 6000,
      },
      {
        label: "Full Stack Development",
        value: "full-stack-development",
        price: 8000,
      },
      {
        label: "MVP Development",
        value: "mvp-development",
        price: 3000,
      },
      {
        label: "Ongoing Development/Support",
        value: "ongoing-development-support",
        price: 1000,
      },
      {
        label: "Not Required",
        value: "not-required",
        price: 0,
      },
    ],
  },
  numOfPages: {
    label: "No. of pages",
    options: [
      {
        label: "1-3",
        value: "1-5-pages",
        price: 500,
      },
      {
        label: "3-8",
        value: "6-10-pages",
        price: 1000,
      },
      {
        label: "8-12",
        value: "11-20-pages",
        price: 1500,
      },
      {
        label: "12-20",
        value: "21-50-pages",
        price: 2500,
      },
      {
        label: "20+",
        value: "50-plus-pages",
        price: 4000,
      },
    ],
  },
  timeline: {
    label: "Timeline",
    options: [
      {
        label: "1-2 Weeks",
        value: "1-2-weeks",
        price: 1000,
      },
      {
        label: "3-4 Weeks",
        value: "3-4-weeks",
        price: 500,
      },
      {
        label: "1-2 Months",
        value: "1-2-months",
        price: 0,
      },
      {
        label: "3-6 Months",
        value: "3-6-months",
        price: -500,
      },
      {
        label: "6+ Months",
        value: "6-plus-months",
        price: -1000,
      },
    ],
  },
  platformType: {
    label: "Platform Type",
    options: [
      {
        label: "Web",
        value: "web",
        price: 1000,
      },
      {
        label: "Web (Responsive)",
        value: "web-and-mobile",
        price: 2000,
      },
      {
        label: "Mobile (iOS/Android)",
        value: "mobile-ios-android",
        price: 3000,
      },
      {
        label: "Desktop Application",
        value: "desktop-application",
        price: 4000,
      },
      {
        label: "Other Platform",
        value: "other-platform",
        price: 2000,
      },
    ],
  },
  maintainanceAndSupport: {
    label: "Maintenance and Support",
    options: [
      {
        label: "No Support",
        value: "no-support",
        price: 0,
      },
      {
        label: "Basic Support (Bug Fixes & Minor Updates)",
        value: "basic-support",
        price: 500,
      },
      {
        label: "Standard Support (Regular Updates & Bug Fixes)",
        value: "standard-support",
        price: 1000,
      },
      {
        label: "Premium Support (Priority Support & Major Updates)",
        value: "premium-support",
        price: 1500,
      },
      {
        label: "24/7 Support",
        value: "24-7-support",
        price: 2000,
      },
    ],
  },
  budget: {
    label: "Budget",
    min: 200,
    max: 10000,
    step: 100,
  },
};

export const countries = [
  { label: "Afghanistan", value: "AF" },
  { label: "Albania", value: "AL" },
  { label: "Algeria", value: "DZ" },
  { label: "Andorra", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Antigua and Barbuda", value: "AG" },
  { label: "Argentina", value: "AR" },
  { label: "Armenia", value: "AM" },
  { label: "Australia", value: "AU" },
  { label: "Austria", value: "AT" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bahrain", value: "BH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbados", value: "BB" },
  { label: "Belarus", value: "BY" },
  { label: "Belgium", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Benin", value: "BJ" },
  { label: "Bhutan", value: "BT" },
  { label: "Bolivia", value: "BO" },
  { label: "Bosnia and Herzegovina", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Brazil", value: "BR" },
  { label: "Brunei", value: "BN" },
  { label: "Bulgaria", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cabo Verde", value: "CV" },
  { label: "Cambodia", value: "KH" },
  { label: "Cameroon", value: "CM" },
  { label: "Canada", value: "CA" },
  { label: "Central African Republic", value: "CF" },
  { label: "Chad", value: "TD" },
  { label: "Chile", value: "CL" },
  { label: "China", value: "CN" },
  { label: "Colombia", value: "CO" },
  { label: "Comoros", value: "KM" },
  { label: "Congo (Congo-Brazzaville)", value: "CG" },
  { label: "Costa Rica", value: "CR" },
  { label: "Croatia", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Cyprus", value: "CY" },
  { label: "Czechia (Czech Republic)", value: "CZ" },
  { label: "Denmark", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominica", value: "DM" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Ecuador", value: "EC" },
  { label: "Egypt", value: "EG" },
  { label: "El Salvador", value: "SV" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Eritrea", value: "ER" },
  { label: "Estonia", value: "EE" },
  { label: "Eswatini", value: "SZ" },
  { label: "Ethiopia", value: "ET" },
  { label: "Fiji", value: "FJ" },
  { label: "Finland", value: "FI" },
  { label: "France", value: "FR" },
  { label: "Gabon", value: "GA" },
  { label: "Gambia", value: "GM" },
  { label: "Georgia", value: "GE" },
  { label: "Germany", value: "DE" },
  { label: "Ghana", value: "GH" },
  { label: "Greece", value: "GR" },
  { label: "Grenada", value: "GD" },
  { label: "Guatemala", value: "GT" },
  { label: "Guinea", value: "GN" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Haiti", value: "HT" },
  { label: "Honduras", value: "HN" },
  { label: "Hungary", value: "HU" },
  { label: "Iceland", value: "IS" },
  { label: "India", value: "IN" },
  { label: "Indonesia", value: "ID" },
  { label: "Iran", value: "IR" },
  { label: "Iraq", value: "IQ" },
  { label: "Ireland", value: "IE" },
  { label: "Israel", value: "IL" },
  { label: "Italy", value: "IT" },
  { label: "Jamaica", value: "JM" },
  { label: "Japan", value: "JP" },
  { label: "Jordan", value: "JO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Kenya", value: "KE" },
  { label: "Kiribati", value: "KI" },
  { label: "Kuwait", value: "KW" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Laos", value: "LA" },
  { label: "Latvia", value: "LV" },
  { label: "Lebanon", value: "LB" },
  { label: "Lesotho", value: "LS" },
  { label: "Liberia", value: "LR" },
  { label: "Libya", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lithuania", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Madagascar", value: "MG" },
  { label: "Malawi", value: "MW" },
  { label: "Malaysia", value: "MY" },
  { label: "Maldives", value: "MV" },
  { label: "Mali", value: "ML" },
  { label: "Malta", value: "MT" },
  { label: "Marshall Islands", value: "MH" },
  { label: "Mauritania", value: "MR" },
  { label: "Mauritius", value: "MU" },
  { label: "Mexico", value: "MX" },
  { label: "Micronesia", value: "FM" },
  { label: "Moldova", value: "MD" },
  { label: "Monaco", value: "MC" },
  { label: "Mongolia", value: "MN" },
  { label: "Montenegro", value: "ME" },
  { label: "Morocco", value: "MA" },
  { label: "Mozambique", value: "MZ" },
  { label: "Myanmar (Burma)", value: "MM" },
  { label: "Namibia", value: "NA" },
  { label: "Nauru", value: "NR" },
  { label: "Nepal", value: "NP" },
  { label: "Netherlands", value: "NL" },
  { label: "New Zealand", value: "NZ" },
  { label: "Nicaragua", value: "NI" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "North Korea", value: "KP" },
  { label: "North Macedonia", value: "MK" },
  { label: "Norway", value: "NO" },
  { label: "Oman", value: "OM" },
  { label: "Pakistan", value: "PK" },
  { label: "Palau", value: "PW" },
  { label: "Palestine", value: "PS" },
  { label: "Panama", value: "PA" },
  { label: "Papua New Guinea", value: "PG" },
  { label: "Paraguay", value: "PY" },
  { label: "Peru", value: "PE" },
  { label: "Philippines", value: "PH" },
  { label: "Poland", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Qatar", value: "QA" },
  { label: "Romania", value: "RO" },
  { label: "Russia", value: "RU" },
  { label: "Rwanda", value: "RW" },
  { label: "Saint Kitts and Nevis", value: "KN" },
  { label: "Saint Lucia", value: "LC" },
  { label: "Saint Vincent and the Grenadines", value: "VC" },
  { label: "Samoa", value: "WS" },
  { label: "San Marino", value: "SM" },
  { label: "Sao Tome and Principe", value: "ST" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Senegal", value: "SN" },
  { label: "Serbia", value: "RS" },
  { label: "Seychelles", value: "SC" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Singapore", value: "SG" },
  { label: "Slovakia", value: "SK" },
  { label: "Slovenia", value: "SI" },
  { label: "Solomon Islands", value: "SB" },
  { label: "Somalia", value: "SO" },
  { label: "South Africa", value: "ZA" },
  { label: "South Korea", value: "KR" },
  { label: "South Sudan", value: "SS" },
  { label: "Spain", value: "ES" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Sudan", value: "SD" },
  { label: "Suriname", value: "SR" },
  { label: "Sweden", value: "SE" },
  { label: "Switzerland", value: "CH" },
  { label: "Syria", value: "SY" },
  { label: "Taiwan", value: "TW" },
  { label: "Tajikistan", value: "TJ" },
  { label: "Tanzania", value: "TZ" },
  { label: "Thailand", value: "TH" },
  { label: "Timor-Leste", value: "TL" },
  { label: "Togo", value: "TG" },
  { label: "Tonga", value: "TO" },
  { label: "Trinidad and Tobago", value: "TT" },
  { label: "Tunisia", value: "TN" },
  { label: "Turkey", value: "TR" },
  { label: "Turkmenistan", value: "TM" },
  { label: "Tuvalu", value: "TV" },
  { label: "Uganda", value: "UG" },
  { label: "Ukraine", value: "UA" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "United Kingdom", value: "GB" },
  { label: "United States", value: "US" },
  { label: "Uruguay", value: "UY" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "Vanuatu", value: "VU" },
  { label: "Vatican City", value: "VA" },
  { label: "Venezuela", value: "VE" },
  { label: "Vietnam", value: "VN" },
  { label: "Yemen", value: "YE" },
  { label: "Zambia", value: "ZM" },
  { label: "Zimbabwe", value: "ZW" },
];
